### ISSUE TITLE
Change hash map in TokenBuffer to use byte array instread of string

### ISSUE THREAD

**Issue by elliVM** [teragrep/dpf_03#11]
HashMap[String, Int]

String -> Array[Byte]

to avoid string conversion

**Comment by kortemik** [comment]
please consider https://www.baeldung.com/java-map-key-byte-array this as well, if scala has a workaround that'd be just cool!

**Comment by kortemik** [comment]
```
val ipaddr = Array[Byte](192.toByte, 168.toByte, 1, 9)
var hashMapName = HashMap(ipaddr->"foo")

scala> hashMapName.contains(ipaddr)
val res2: Boolean = true

scala> val ipaddr2 = Array[Byte](192.toByte, 168.toByte, 1, 9)
val ipaddr2: Array[Byte] = Array(-64, -88, 1, 9)

scala> hashMapName.contains(ipaddr2)
val res3: Boolean = false
```

problem persists. perhaps it is possible to use ByteBuffer.wrap around the array to be able to use it as a key.
